const BOOKING_STATES = {
  SELECT_PET: 'SELECT_PET',
  COLLECT_REASON: 'COLLECT_REASON',
  COLLECT_DATE: 'COLLECT_DATE',
  COLLECT_TIME: 'COLLECT_TIME',
  SHOW_CLINICS: 'SHOW_CLINICS',
  CONFIRM_BOOKING: 'CONFIRM_BOOKING',
  COMPLETED: 'COMPLETED'
};

module.exports = BOOKING_STATES;
